# This file contains values from Cookiecutter

default_context:
  project_name: "uacp"
  project_description: "Universal Agent Communication Protocol"
  organization: "Undertone0809"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "Undertone0809"
  email: "zeeland4work@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
